#  Guide: https://hlfshell.ai/posts/repeatable-ros-environments/
# Install ROS 2: https://docs.ros.org/en/foxy/Installation/Ubuntu-Install-Debians.html
# Example file for Ubuntu desktop: https://gist.github.com/niw/bed28f823b4ebd2c504285ff99c1b2c2

# Vagrantfile for Ubuntu 22.04 with 30GB memory and bridged network
Vagrant.configure("2") do |config|
  # Specify the Ubuntu 22.04 base box
  config.vm.box = "ubuntu/jammy64" # Ubuntu 22.04 (Jammy Jellyfish)

  # VM settings
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 16384  # Set memory to 16 GB (16384 MB)
    vb.cpus = 4        # Optional: You can configure CPU cores as needed

    # Video
    vb.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
    vb.customize ["modifyvm", :id, "--vram", "256"]
    vb.customize ["modifyvm", :id, "--accelerate3d", "on"]

    # Clipboard
    vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
  end

  # Bridged network configuration
  config.vm.network "public_network" # bridge: "en0: Wi-Fi" # Adjust bridge interface as needed

  # Currently "ubuntu/bionic64" on VirtualBox requires `type: "virtualbox"`
  # to make synced folder works.
  # config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  config.vm.synced_folder "./src/", "/home/vagrant/src/"

  # Additional settings (e.g., provisioning)

  config.vm.provision "shell", inline: <<-SHELL
    echo "==========================================\n"
    echo "Initial OS + Ubuntu Desktop Setup\n"
    echo "==========================================\n\n"

    apt-get update
    apt-get install -y --no-install-recommends ubuntu-desktop
    apt-get install -y --no-install-recommends virtualbox-dkms virtualbox-guest-utils virtualbox-guest-x11

    # Add `vagrant` to Administrator
    sudo usermod -a -G sudo vagrant
  SHELL

  config.vm.provision "shell", inline: <<-SHELL
    echo "\n\n"
    echo "==========================================\n"
    echo "Installing ROS Humble\n"
    echo "==========================================\n\n"

    echo "\n\n"
    echo "-------------\n"
    echo "Locale Setup\n"
    echo "-------------\n\n"

    apt-get update
    apt-get install -y --no-install-recommends locales
    locale-gen en_US en_US.UTF-8
    update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
    export LANG=en_US.UTF-8

    echo "\n\n"
    echo "-------------\n"
    echo "Add Additional Repositories\n"
    echo "-------------\n\n"

    apt-get update
    apt-get install -y --no-install-recommends software-properties-common
    add-apt-repository universe

    apt-get update
    apt-get install -y --no-install-recommends curl
    curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg

    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null

    # Finally, refresh the package lists:
    # Recommended as ROS2 is tied tightly to ubuntu releases apparently
    apt-get update
    apt-get upgrade

    echo "\n\n"
    echo "-------------\n"
    echo "Install ROS2\n"
    echo "-------------\n\n"

    apt-get update
    apt-get install -y --no-install-recommends ros-humble-desktop # Includes rviz + demos
    apt-get install -y --no-install-recommends ros-humble-turtlebot4-desktop
  SHELL

  config.vm.provision "shell", inline: <<-SHELL
    echo "\n\n"
    echo "==========================================\n"
    echo "Installing other tools\n"
    echo "==========================================\n\n"

    apt-get update
    apt-get install -y --no-install-recommends python3-argcomplete python3-colcon-common-extensions python3-colcon-mixin python3-vcstool python3-rosdep
    apt-get install -y --no-install-recommends build-essential git vim wget
    apt-get install -y --no-install-recommends gnome-tweaks

    # clean up
    rm -rf /var/lib/apt/lists/*
  SHELL
end
